# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Common
pod 'SVProgressHUD'
pod 'AgoraRtcEngine_iOS'
pod 'AgoraStreamingKit_iOS'

target 'LiveStreaming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveStreaming

end

target 'LiveStreamingWithFU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveStreamingWithFU
  pod 'Nama', '~> 7.1.0'

end
